FROM mcr.microsoft.com/devcontainers/base:jammy

RUN apt-get update 
RUN apt-get install -y gdb file pip python2
# RUN bash -c "$(curl -fsSL https://gef.blah.cat/sh)"
# RUN cp ~/.gdbinit /home/vscode/.gdbinit
# RUN gdb -nx -ex 'pi print(sys.version)' -ex quit